Change size_t flexCount type to _C2FlexCount
C++ does not allow defining a class-specific
`operator new(size_t, size_t)` placement allocation method as that
would call the non-placement `operator delete(void*, size_t)`. While
the new operator is used as an allocating allocation method, after
upgrading to clang-r547379, the compiler diagnoses this mismatch:

error: 'new' expression with placement arguments refers to non-placement 'operator delete'

Bug: http://b/392522623
Test: presubmit
Change-Id: Iff1d8dcaf10319efb52d1b5574003f80fe027bb7